# Generated by Django 5.2.3 on 2025-06-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='comm_images/')),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
    ]
