# Generated by Django 5.2.3 on 2025-06-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('global_pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.globalpid')),
                ('co_content', models.TextField(max_length=500, verbose_name='Comentario')),
                ('anon', models.BooleanField(default=False)),
                ('creat_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('is_reply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('global_pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.globalpid')),
                ('po_content', models.TextField(max_length=500, verbose_name='post')),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('anon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_pid', models.IntegerField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
