# Generated by Django 5.2.3 on 2025-06-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='PoContent',
            new_name='po_content',
        ),
    ]
