# Generated by Django 5.2.3 on 2025-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_report_moderator_report_review_notes_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
